[package]
name = "composition_royalty_pool_plugin"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
composition_royalty_pool = { git = "https://github.com/misofm/musicos-actions.git", subdir = "composition_royalty_pool", rev = "1e5a67d5bbe093beef1d4749d7d39f9c7d454a53" }
vault = { git = "https://github.com/misofm/vault.git", rev = "8a4d1c0edbc120efc642a682308662e2a0b7f407" }
musicos = { git = "https://github.com/misofm/musicos.git", rev = "b3d5d4005fe36044d90e318f864dbc8b01de41da" }
royalty_pool = { git = "https://github.com/misofm/royalty-pool.git", rev = "de389b508708fb5c7a14ed3548e871626c844bdc" }
hikida = { git = "https://github.com/unconfirmedlabs/hikida.git", rev = "4abe4c1ff482655693698fa6ab8a6e2b58f8c635", modes = ["test"] }
