[package]
name = "recording_royalty_pool_plugin"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
recording_royalty_pool = { git = "https://github.com/misofm/musicos-actions.git", subdir = "recording_royalty_pool", rev = "1238a44dc95a2f60aa01d9eac2bbfc4cbfca84ea" }
vault = { git = "https://github.com/misofm/vault.git", rev = "70c2d3a51fa7f4ce8ad471db8ec51a841dda9e42" }
musicos = { git = "https://github.com/misofm/musicos.git", rev = "e56c4cbc0d9673f6422e365364b128d0813341ac" }
royalty_pool = { git = "https://github.com/misofm/royalty-pool.git", rev = "3fc2eee57a128874f9405cf218c613627824dc8e" }
