[package]
name = "recording_royalty_pool_plugin"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
recording_royalty_pool = { git = "https://github.com/misofm/protocol-actions.git", subdir = "recording_royalty_pool", rev = "56cb0b71d7fa1b2221e02216f8437ae2ede5ceff" }
vault = { git = "https://github.com/misofm/vault.git", rev = "6b55f9fe8d89f7a7974cb843b10b9827fe13ef0f" }
miso = { git = "https://github.com/misofm/protocol.git", rev = "ffa0e38b8ba4815d81de1076101ea37d2c71c623" }
royalty_pool = { git = "https://github.com/misofm/royalty-pool.git", rev = "0b40a6f5d37c595d29acd7f6ebbee0a11177482f" }
