[package]
name = "release_revenue_distributor"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { git = "https://github.com/misonetwork/protocol.git", rev = "7c13e40a2613fd01a42353c2e98e614cfa671449" }
vault = { git = "https://github.com/misofm/vault.git", rev = "2c799916e45befaa471ccef1918e5b8c42aeddc4" }
hikida = { git = "https://github.com/unconfirmedlabs/hikida.git", rev = "e88c6fa88348bc2764823cf3666d7ca5e08b2f4f" }
