[package]
name = "release_revenue_distributor_plugin"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
release_revenue_distributor = { git = "https://github.com/misofm/musicos-actions.git", subdir = "release_revenue_distributor", rev = "9985ad7da357f8ae9de700338ba6a40b316362eb" }
vault = { git = "https://github.com/misofm/vault.git", rev = "dad40fbcb3c6e0596c210828193302dd3552ff82" }
musicos = { git = "https://github.com/misofm/musicos.git", rev = "f7a2be77ecc4429a1c5ff70800490b1946b1defb" }
composition_royalty_pool = { git = "https://github.com/misofm/musicos-actions.git", subdir = "composition_royalty_pool", rev = "9985ad7da357f8ae9de700338ba6a40b316362eb", modes = ["test"] }
composition_routed_stake = { git = "https://github.com/misofm/musicos-actions.git", subdir = "composition_routed_stake", rev = "9985ad7da357f8ae9de700338ba6a40b316362eb", modes = ["test"] }
recording_royalty_pool = { git = "https://github.com/misofm/musicos-actions.git", subdir = "recording_royalty_pool", rev = "9985ad7da357f8ae9de700338ba6a40b316362eb", modes = ["test"] }
royalty_pool = { git = "https://github.com/misofm/royalty-pool.git", rev = "3aa2461c8abc8dc1153a39669fbac8f346bf0aa9", modes = ["test"] }
routed_stake = { git = "https://github.com/misofm/routed-stake.git", rev = "7ca690e81b39c8be1b3dc9e52764e5beebcc12f0", modes = ["test"] }
